#!/bin/bash

export THIS_DIR=$PWD

  


echo "> Installing Paper..."
cd JavaInstallScripts
chmod +x *
./PaperInstall



#Installing all the dependencise
sudo apt install -y -qq screen neofetch 

echo "export PATH=$PATH:/some/new/path" > ~/.profile
echo "> Dependencies Installtion Completed!"

#Downloading ngrok && Downloading Minecraft Server
mkdir server 



# Backup install playit.gg in case if first one doesn't download
echo "> Installing Playit.gg..."
cd ..
#wget "https://playit.gg/downloads/playit-linux_64-0.4.2-rc1" -O playit 
wget -q "https://playit.gg/downloads/playit-linux_64-0.4.6" -O playit
chmod +x playit
echo "> Playit.gg Installation Completed!"
echo ""



./startserver

